version: '2'

services:
  alist:
    image: hub.qucheng.com/app/alist:${TAG:-latest}
    container_name: alist
    ports:
      - '5244:5244'
    volumes:
      - 'data:/apps/alist/data/'
    environment:
      - ALIST_ADMIN_PASSWORD=qucheng123

# persistence
volumes:
  data:
    driver: local
